baseURL = "https://2024365.xyz/"
languageCode = "zh-cn"
title = "Protomyst's Space"
theme = "PaperMod"

[params]
mainSections = ["post"]
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true

[params.homeInfoParams]
Title = "欢迎来到 Protomyst 的文档站"
Content = "在喧嚣时代中静心思考，用文字传递理性与希望。"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Protomyst"

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
category = "categories"
tag = "tags"

[menu]
main = [
    {identifier = "archives", name = "Archives", url = "/archives/", weight = 10},
    {identifier = "categories", name = "Categories", url = "/categories/", weight = 20},
    {identifier = "search", name = "Search", url = "/search/", weight = 30},
    {identifier = "tags", name = "Tags", url = "/tags/", weight = 40}
]